/**
 * Field limits come from core's contract (ADR-025), not from numbers typed
 * here. src/limits.ts is generated by scripts/generate-limits.mjs; this file
 * proves the registered tools use exactly those values, so a hand-edited
 * number in src/tools.ts fails rather than quietly narrowing or widening what
 * the engine accepts.
 *
 * What the drift cost before 0.11: `top_k` refused anything over 50 while the
 * engine had accepted 500 since June; `domain` had no length here while the
 * engine rejects over 100 characters; `concepts` had no count; `max_uses` had
 * no ceiling; and the `top_k` description promised a default of 5 where the
 * engine uses 10.
 *
 * The other half of the chain is `npm run limits:check`, which refetches the
 * contract and fails if this file's values are no longer what core publishes.
 * It needs the network, so it runs in its own scheduled workflow rather than
 * on every pull request.
 */

import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { CORE_CONTRACT, CORE_LIMITS } from "../src/limits.js";
import { startMemoryServer, type Harness } from "./harness.js";

interface JsonSchemaField {
  type?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  maxItems?: number;
}

let mcp: Harness;
let fields: Record<string, Record<string, JsonSchemaField>>;

beforeAll(async () => {
  mcp = await startMemoryServer();
  const { tools } = await mcp.client.listTools();
  fields = Object.fromEntries(
    tools.map((t) => [t.name, (t.inputSchema.properties ?? {}) as Record<string, JsonSchemaField>]),
  );
});
afterAll(async () => {
  await mcp.close();
});

describe("every bounded field carries core's limit", () => {
  const CASES: Array<[tool: string, field: string, expected: Partial<JsonSchemaField>]> = [
    ["memory_write", "content", {
      minLength: CORE_LIMITS.writeContent.minLength,
      maxLength: CORE_LIMITS.writeContent.maxLength,
    }],
    ["memory_write", "concepts", { maxItems: CORE_LIMITS.writeConcepts.maxItems }],
    ["memory_write", "domain", { maxLength: CORE_LIMITS.domain.maxLength }],
    ["memory_read", "query", {
      minLength: CORE_LIMITS.readQuery.minLength,
      maxLength: CORE_LIMITS.readQuery.maxLength,
    }],
    ["memory_read", "top_k", {
      minimum: CORE_LIMITS.readTopK.minimum,
      maximum: CORE_LIMITS.readTopK.maximum,
    }],
    ["memory_list_recent", "limit", {
      minimum: CORE_LIMITS.recentLimit.minimum,
      maximum: CORE_LIMITS.recentLimit.maximum,
    }],
    ["memory_list_recent", "cursor", { maxLength: CORE_LIMITS.recentCursor.maxLength }],
    ["memory_feedback", "outcome", {
      minimum: CORE_LIMITS.feedbackOutcome.minimum,
      maximum: CORE_LIMITS.feedbackOutcome.maximum,
    }],
    ["memory_create_room", "name", {
      minLength: CORE_LIMITS.roomName.minLength,
      maxLength: CORE_LIMITS.roomName.maxLength,
    }],
    ["memory_create_room", "description", { maxLength: CORE_LIMITS.roomDescription.maxLength }],
    ["memory_invite_to_room", "expires_in_days", {
      minimum: CORE_LIMITS.inviteExpiresInDays.minimum,
      maximum: CORE_LIMITS.inviteExpiresInDays.maximum,
    }],
    ["memory_invite_to_room", "max_uses", {
      minimum: CORE_LIMITS.inviteMaxUses.minimum,
      maximum: CORE_LIMITS.inviteMaxUses.maximum,
    }],
  ];

  it.each(CASES)("%s.%s", (tool, field, expected) => {
    const schema = fields[tool]?.[field];
    expect(schema, `${tool} has no ${field}`).toBeTruthy();
    for (const [key, value] of Object.entries(expected)) {
      expect(schema![key as keyof JsonSchemaField], `${tool}.${field}.${key}`).toBe(value);
    }
  });

  it("the read reaches the engine's real ceiling, not the old 50", () => {
    expect(CORE_LIMITS.readTopK.maximum).toBeGreaterThan(50);
    expect(fields.memory_read.top_k.maximum).toBe(CORE_LIMITS.readTopK.maximum);
  });

  it("states the engine's own default for top_k, which is what an omitted field gets", async () => {
    const { tools } = await mcp.client.listTools();
    const description = (
      tools.find((t) => t.name === "memory_read")?.inputSchema.properties as Record<
        string,
        { description?: string }
      >
    ).top_k.description;
    expect(description).toContain(`default: ${CORE_LIMITS.readTopK.default}`);
  });

  it("records where the limits came from", () => {
    expect(CORE_CONTRACT.url).toMatch(/^https:\/\/.+\/openapi\.json$/);
    expect(CORE_CONTRACT.apiVersion).toMatch(/^\d+\.\d+\.\d+$/);
  });
});

describe("a value past core's limit is refused here, before the request", () => {
  it.each([
    ["memory_read", { query: "x", top_k: CORE_LIMITS.readTopK.maximum + 1 }],
    ["memory_write", { content: "x", domain: "d".repeat(CORE_LIMITS.domain.maxLength + 1) }],
    ["memory_write", { content: "x", concepts: Array(CORE_LIMITS.writeConcepts.maxItems + 1).fill("c") }],
    ["memory_list_recent", { limit: CORE_LIMITS.recentLimit.maximum + 1 }],
  ])("%s", async (tool, args) => {
    mcp.reset();
    const res = await mcp.call(tool, args as Record<string, unknown>);
    expect(res.isError).toBe(true);
    expect(mcp.calls).toHaveLength(0);
  });
});
