#!/usr/bin/env node
/**
 * install-hooks.mjs
 *
 * Installs the optional pre-push hook for local drift detection. The hook
 * runs `npm run verify:configs` before every push and aborts if any of the
 * 15 generated artifacts is out of sync with src/configs/source.json.
 *
 * The hook is per-clone (.git/hooks/ is not committed) and opt-in. CI is
 * the authoritative gate — see .github/workflows/verify-configs.yml.
 *
 * Usage: npm run install-hooks
 */

import {
  writeFileSync,
  chmodSync,
  existsSync,
  mkdirSync,
} from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const HOOKS_DIR = resolve(ROOT, ".git/hooks");
const HOOK_PATH = resolve(HOOKS_DIR, "pre-push");

if (!existsSync(resolve(ROOT, ".git"))) {
  console.error(
    "✗ Not a git repo (no .git directory found at " + ROOT + ").",
  );
  console.error("  Cannot install pre-push hook.");
  process.exit(1);
}

mkdirSync(HOOKS_DIR, { recursive: true });

const HOOK_BODY = `#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.mjs.
# Aborts the push if any of the 15 distribution artifacts has drifted from
# src/configs/source.json. Re-run install-hooks after pulling generator changes.
#
# To bypass for a one-off (NOT recommended for branches targeting main):
#   git push --no-verify

set -e

# Find repo root so the hook works regardless of where 'git push' was invoked.
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if ! command -v node >/dev/null 2>&1; then
  echo "pre-push: node not found in PATH; skipping drift check"
  exit 0
fi

echo "pre-push: verifying distribution config drift..."
if ! node scripts/generate-configs.mjs --check; then
  echo ""
  echo "✗ Push aborted: distribution configs are out of sync with src/configs/source.json"
  echo "  Run \\\`npm run generate:configs\\\` to fix, commit the result, then push again."
  echo "  See CONTRIBUTING.md for details."
  exit 1
fi
`;

writeFileSync(HOOK_PATH, HOOK_BODY, "utf8");
chmodSync(HOOK_PATH, 0o755);

console.log("✓ Installed pre-push hook at " + HOOK_PATH);
console.log("  It will run `node scripts/generate-configs.mjs --check`");
console.log("  before every push and abort on drift.");
console.log("");
console.log("  To remove: rm " + HOOK_PATH);
console.log("  To bypass once: git push --no-verify");
